-- PandaStore initial schema for an empty Supabase/PostgreSQL database.
-- Generated from the current 20 JPA entities with Hibernate ORM 7.4.5.Final
-- and Spring Boot's naming strategies; includes the product_categories join table.
-- Run the COMPLETE file once as postgres in Supabase SQL Editor.
-- All DDL and security settings commit together; an error rolls everything back.
-- Existing tables/roles are intentionally rejected rather than overwritten.
-- No demo users or seed data are included.

begin;
set local lock_timeout = '5s';
set local statement_timeout = '60s';

-- Dedicated backend role: no login until its password is configured separately.
-- Spring Security remains responsible for each application's user permissions.
create role pandastore_backend nologin nosuperuser nocreatedb nocreaterole
    noreplication nobypassrls noinherit;
-- Allow the administrative owner to manage/test this role, including on PostgreSQL 16+.
grant pandastore_backend to postgres;
grant usage on schema public to pandastore_backend;
alter role pandastore_backend set search_path = public;

-- Tables, enum checks, unique constraints and foreign keys from Hibernate.

create table public.addresses (
    is_default boolean not null,
    address_id bigint generated by default as identity,
    customer_id bigint not null,
    postal_code varchar(10) not null,
    phone_number varchar(20) not null,
    district varchar(100) not null,
    province varchar(100) not null,
    receiver_name varchar(100) not null,
    address_line varchar(255) not null,
    primary key (address_id)
);

create table public.auth_sessions (
    expires_at timestamp(6) with time zone not null,
    user_id bigint not null,
    token_hash varchar(64) not null,
    credential_hash varchar(255) not null,
    primary key (token_hash)
);

create table public.cart_items (
    is_selected boolean not null,
    quantity integer not null,
    cart_id bigint not null,
    cart_item_id bigint generated by default as identity,
    product_id bigint not null,
    primary key (cart_item_id)
);

create table public.carts (
    cart_id bigint generated by default as identity,
    customer_id bigint not null unique,
    primary key (cart_id)
);

create table public.categories (
    category_id bigint generated by default as identity,
    category_name varchar(100) not null,
    description varchar(255),
    primary key (category_id)
);

create table public.customers (
    customer_id bigint generated by default as identity,
    user_id bigint not null unique,
    phone_number varchar(20),
    full_name varchar(100),
    primary key (customer_id)
);

create table public.notifications (
    is_read boolean not null,
    created_at timestamp(6) not null,
    notification_id bigint generated by default as identity,
    recipient_user_id bigint not null,
    type varchar(30) not null check ((type in ('PAYMENT_SUCCESS','NEW_ORDER_FOR_SELLER','ORDER_SHIPPED','NEW_REVIEW','SELLER_APPROVED','NEW_SELLER_APPLICATION'))),
    title varchar(150) not null,
    message TEXT not null,
    primary key (notification_id)
);

create table public.order_groups (
    grand_total numeric(12,2) not null,
    total_discount numeric(12,2),
    total_products_amount numeric(12,2) not null,
    total_shipping_fee numeric(12,2) not null,
    created_at timestamp(6) not null,
    customer_id bigint not null,
    order_group_id bigint generated by default as identity,
    shipping_address_id bigint not null,
    payment_status varchar(25) not null check ((payment_status in ('PENDING','PAID','PARTIALLY_REFUNDED','REFUNDED','FAILED'))),
    group_number varchar(36) not null unique,
    primary key (order_group_id)
);

create table public.order_items (
    is_reviewed boolean not null,
    quantity integer not null,
    total_price numeric(12,2) not null,
    unit_price numeric(12,2) not null,
    order_id bigint not null,
    order_item_id bigint generated by default as identity,
    product_id bigint not null,
    product_name varchar(200) not null,
    primary key (order_item_id)
);

create table public.orders (
    seller_discount numeric(12,2),
    shipping_fee numeric(12,2) not null,
    subtotal numeric(12,2) not null,
    total_amount numeric(12,2) not null,
    completed_at timestamp(6),
    created_at timestamp(6) not null,
    order_group_id bigint not null,
    order_id bigint generated by default as identity,
    seller_id bigint not null,
    shipped_at timestamp(6),
    order_status varchar(30) not null check ((order_status in ('PENDING_PAYMENT','WAITING_SELLER_CONFIRM','PREPARING','SHIPPED','COMPLETED','CANCELLED'))),
    sub_order_number varchar(36) not null unique,
    shipping_method varchar(100),
    rejection_reason varchar(255),
    primary key (order_id)
);

create table public.payments (
    amount numeric(12,2) not null,
    refunded_amount numeric(12,2),
    order_group_id bigint not null unique,
    paid_at timestamp(6),
    payment_id bigint generated by default as identity,
    status varchar(25) not null check ((status in ('PENDING','SUCCESS','FAILED','PARTIALLY_REFUNDED','REFUNDED'))),
    payment_method varchar(30) not null check ((payment_method in ('CREDIT_CARD','PROMPTPAY','BANK_TRANSFER','WALLET'))),
    gateway_transaction_id varchar(100),
    primary key (payment_id)
);

create table public.product_categories (
    category_id bigint not null,
    product_id bigint not null,
    primary key (category_id, product_id)
);

create table public.product_images (
    display_order integer not null,
    is_primary boolean not null,
    image_id bigint generated by default as identity,
    product_id bigint not null,
    image_url varchar(255) not null,
    primary key (image_id)
);

create table public.products (
    average_rating numeric(3,2),
    price numeric(12,2) not null,
    review_count integer not null,
    stock integer not null,
    created_at timestamp(6) not null,
    product_id bigint generated by default as identity,
    seller_id bigint not null,
    updated_at timestamp(6),
    status varchar(20) not null check ((status in ('ACTIVE','OUT_OF_STOCK','INACTIVE'))),
    name varchar(200) not null,
    description TEXT,
    shipping_info varchar(255),
    primary key (product_id)
);

create table public.review_replies (
    replied_at timestamp(6) not null,
    reply_id bigint generated by default as identity,
    review_id bigint not null unique,
    seller_id bigint not null,
    reply_message TEXT not null,
    primary key (reply_id)
);

create table public.reviews (
    is_auto_review boolean not null,
    rating integer not null,
    created_at timestamp(6) not null,
    customer_id bigint not null,
    order_item_id bigint not null unique,
    product_id bigint not null,
    review_id bigint generated by default as identity,
    updated_at timestamp(6),
    comment TEXT,
    primary key (review_id)
);

create table public.seller_applications (
    application_id bigint generated by default as identity,
    created_at timestamp(6) not null,
    reviewed_at timestamp(6),
    reviewed_by bigint,
    user_id bigint not null,
    id_card_number varchar(13) not null,
    shop_phone varchar(20) not null,
    status varchar(20) not null check ((status in ('PENDING','APPROVED','REJECTED','NEED_MORE_DOC'))),
    bank_account_number varchar(30) not null,
    bank_account_name varchar(100) not null,
    bank_name varchar(100) not null,
    seller_first_name varchar(100) not null,
    seller_last_name varchar(100) not null,
    shop_email varchar(100) not null,
    shop_name varchar(100) not null,
    admin_note TEXT,
    bank_book_image_url varchar(255) not null,
    id_card_image_url varchar(255) not null,
    shop_address varchar(255) not null,
    shop_description TEXT not null,
    primary key (application_id)
);

create table public.seller_bank_accounts (
    bank_account_id bigint generated by default as identity,
    seller_id bigint not null,
    account_number varchar(30) not null,
    account_name varchar(100) not null,
    bank_name varchar(100) not null,
    proof_image_url varchar(255) not null,
    primary key (bank_account_id)
);

create table public.sellers (
    rating numeric(3,2),
    created_at timestamp(6) not null,
    seller_id bigint generated by default as identity,
    user_id bigint not null unique,
    shop_phone varchar(20) not null,
    status varchar(20) not null check ((status in ('PENDING','ACTIVE','REJECTED','SUSPENDED'))),
    shop_email varchar(100) not null,
    shop_name varchar(100) not null unique,
    shop_address varchar(255) not null,
    shop_description TEXT,
    primary key (seller_id)
);

create table public.shipments (
    delivered_at timestamp(6),
    order_id bigint not null unique,
    shipment_id bigint generated by default as identity,
    shipped_at timestamp(6),
    shipping_status varchar(25) not null check ((shipping_status in ('PENDING','SHIPPED','DELIVERED'))),
    courier_name varchar(100) not null,
    tracking_number varchar(100) not null,
    primary key (shipment_id)
);

create table public.users (
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    user_id bigint generated by default as identity,
    role varchar(20) not null check ((role in ('CUSTOMER','SELLER','ADMIN'))),
    status varchar(20) not null check ((status in ('ACTIVE','SUSPENDED','INACTIVE'))),
    username varchar(50) not null unique,
    email varchar(100) not null unique,
    password_hash varchar(255) not null,
    primary key (user_id)
);

alter table public.addresses 
   add constraint FKhrpf5e8dwasvdc5cticysrt2k 
   foreign key (customer_id) 
   references public.customers;

alter table public.auth_sessions 
   add constraint FKpu507182mdfutajr71rgk67l 
   foreign key (user_id) 
   references public.users;

alter table public.cart_items 
   add constraint FKpcttvuq4mxppo8sxggjtn5i2c 
   foreign key (cart_id) 
   references public.carts;

alter table public.cart_items 
   add constraint FK1re40cjegsfvw58xrkdp6bac6 
   foreign key (product_id) 
   references public.products;

alter table public.carts 
   add constraint FK8ba3sryid5k8a9kidpkvqipyt 
   foreign key (customer_id) 
   references public.customers;

alter table public.customers 
   add constraint FKrh1g1a20omjmn6kurd35o3eit 
   foreign key (user_id) 
   references public.users;

alter table public.notifications 
   add constraint FKt8ievafor22iuvg5sd4p7lhbk 
   foreign key (recipient_user_id) 
   references public.users;

alter table public.order_groups 
   add constraint FKrrsq16lttblmc1atv67np4gg1 
   foreign key (customer_id) 
   references public.customers;

alter table public.order_groups 
   add constraint FK11l795m8in49iunw9bd1i9i22 
   foreign key (shipping_address_id) 
   references public.addresses;

alter table public.order_items 
   add constraint FKbioxgbv59vetrxe0ejfubep1w 
   foreign key (order_id) 
   references public.orders;

alter table public.order_items 
   add constraint FKocimc7dtr037rh4ls4l95nlfi 
   foreign key (product_id) 
   references public.products;

alter table public.orders 
   add constraint FK2672cpdpsk4t6bahipaxqu5db 
   foreign key (order_group_id) 
   references public.order_groups;

alter table public.orders 
   add constraint FKbdhiwrh9a9c3gmlfvx8f0cvyh 
   foreign key (seller_id) 
   references public.sellers;

alter table public.payments 
   add constraint FKilicvyqhkll91wkqrc00lsj2o 
   foreign key (order_group_id) 
   references public.order_groups;

alter table public.product_categories 
   add constraint FKd112rx0alycddsms029iifrih 
   foreign key (category_id) 
   references public.categories;

alter table public.product_categories 
   add constraint FKlda9rad6s180ha3dl1ncsp8n7 
   foreign key (product_id) 
   references public.products;

alter table public.product_images 
   add constraint FKqnq71xsohugpqwf3c9gxmsuy 
   foreign key (product_id) 
   references public.products;

alter table public.products 
   add constraint FKepbha8uixgrmnejm27n6e1kkd 
   foreign key (seller_id) 
   references public.sellers;

alter table public.review_replies 
   add constraint FKk8ng2k5mf1sf7mpkiuk29p3ee 
   foreign key (review_id) 
   references public.reviews;

alter table public.review_replies 
   add constraint FKcp1gtm534be81y9lqu4xo9afl 
   foreign key (seller_id) 
   references public.sellers;

alter table public.reviews 
   add constraint FK4sm0k8kw740iyuex3vwwv1etu 
   foreign key (customer_id) 
   references public.customers;

alter table public.reviews 
   add constraint FK2x2x74lnliqmt91bc1w95ll8n 
   foreign key (order_item_id) 
   references public.order_items;

alter table public.reviews 
   add constraint FKpl51cejpw4gy5swfar8br9ngi 
   foreign key (product_id) 
   references public.products;

alter table public.seller_applications 
   add constraint FK18f247gqrpn0yljsrqmpltjpa 
   foreign key (reviewed_by) 
   references public.users;

alter table public.seller_applications 
   add constraint FK69gdam04mx3lfr82sok9cb4ba 
   foreign key (user_id) 
   references public.users;

alter table public.seller_bank_accounts 
   add constraint FKjjhncvv4imykflrwfrbolf4dh 
   foreign key (seller_id) 
   references public.sellers;

alter table public.sellers 
   add constraint FKjnqi0k1rlkb8h3fus7f5wfqd1 
   foreign key (user_id) 
   references public.users;

alter table public.shipments 
   add constraint FKrnt4wht95lxxplspltrg9681s 
   foreign key (order_id) 
   references public.orders;

-- FK indexes (skip columns already covered by a primary/unique index).
create index idx_addresses_customer_id on public.addresses (customer_id, is_default desc, address_id);
create index idx_auth_sessions_user_id on public.auth_sessions (user_id);
create index idx_cart_items_cart_id on public.cart_items (cart_id);
create index idx_cart_items_product_id on public.cart_items (product_id);
create index idx_notifications_recipient_user_id on public.notifications (recipient_user_id, created_at desc, notification_id desc);
create index idx_order_groups_customer_id on public.order_groups (customer_id);
create index idx_order_groups_shipping_address_id on public.order_groups (shipping_address_id);
create index idx_order_items_order_id on public.order_items (order_id);
create index idx_order_items_product_id on public.order_items (product_id);
create index idx_orders_order_group_id on public.orders (order_group_id);
create index idx_orders_seller_id on public.orders (seller_id);
create index idx_product_categories_product_id on public.product_categories (product_id);
create index idx_product_images_product_id on public.product_images (product_id, display_order);
create index idx_products_seller_id on public.products (seller_id);
create index idx_review_replies_seller_id on public.review_replies (seller_id);
create index idx_reviews_customer_id on public.reviews (customer_id);
create index idx_reviews_product_id on public.reviews (product_id, created_at desc);
create index idx_seller_applications_reviewed_by on public.seller_applications (reviewed_by);
create index idx_seller_applications_user_id on public.seller_applications (user_id);
create index idx_seller_bank_accounts_seller_id on public.seller_bank_accounts (seller_id);
create index idx_auth_sessions_expires_at on public.auth_sessions (expires_at);

-- Backend-only access. No Data API policies are granted to client roles.
alter table public.addresses enable row level security;
revoke all on table public.addresses from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.addresses to pandastore_backend;
create policy pandastore_backend_access on public.addresses
    for all to pandastore_backend using (true) with check (true);

alter table public.auth_sessions enable row level security;
revoke all on table public.auth_sessions from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.auth_sessions to pandastore_backend;
create policy pandastore_backend_access on public.auth_sessions
    for all to pandastore_backend using (true) with check (true);

alter table public.cart_items enable row level security;
revoke all on table public.cart_items from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.cart_items to pandastore_backend;
create policy pandastore_backend_access on public.cart_items
    for all to pandastore_backend using (true) with check (true);

alter table public.carts enable row level security;
revoke all on table public.carts from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.carts to pandastore_backend;
create policy pandastore_backend_access on public.carts
    for all to pandastore_backend using (true) with check (true);

alter table public.categories enable row level security;
revoke all on table public.categories from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.categories to pandastore_backend;
create policy pandastore_backend_access on public.categories
    for all to pandastore_backend using (true) with check (true);

alter table public.customers enable row level security;
revoke all on table public.customers from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.customers to pandastore_backend;
create policy pandastore_backend_access on public.customers
    for all to pandastore_backend using (true) with check (true);

alter table public.notifications enable row level security;
revoke all on table public.notifications from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.notifications to pandastore_backend;
create policy pandastore_backend_access on public.notifications
    for all to pandastore_backend using (true) with check (true);

alter table public.order_groups enable row level security;
revoke all on table public.order_groups from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.order_groups to pandastore_backend;
create policy pandastore_backend_access on public.order_groups
    for all to pandastore_backend using (true) with check (true);

alter table public.order_items enable row level security;
revoke all on table public.order_items from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.order_items to pandastore_backend;
create policy pandastore_backend_access on public.order_items
    for all to pandastore_backend using (true) with check (true);

alter table public.orders enable row level security;
revoke all on table public.orders from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.orders to pandastore_backend;
create policy pandastore_backend_access on public.orders
    for all to pandastore_backend using (true) with check (true);

alter table public.payments enable row level security;
revoke all on table public.payments from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.payments to pandastore_backend;
create policy pandastore_backend_access on public.payments
    for all to pandastore_backend using (true) with check (true);

alter table public.product_categories enable row level security;
revoke all on table public.product_categories from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.product_categories to pandastore_backend;
create policy pandastore_backend_access on public.product_categories
    for all to pandastore_backend using (true) with check (true);

alter table public.product_images enable row level security;
revoke all on table public.product_images from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.product_images to pandastore_backend;
create policy pandastore_backend_access on public.product_images
    for all to pandastore_backend using (true) with check (true);

alter table public.products enable row level security;
revoke all on table public.products from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.products to pandastore_backend;
create policy pandastore_backend_access on public.products
    for all to pandastore_backend using (true) with check (true);

alter table public.review_replies enable row level security;
revoke all on table public.review_replies from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.review_replies to pandastore_backend;
create policy pandastore_backend_access on public.review_replies
    for all to pandastore_backend using (true) with check (true);

alter table public.reviews enable row level security;
revoke all on table public.reviews from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.reviews to pandastore_backend;
create policy pandastore_backend_access on public.reviews
    for all to pandastore_backend using (true) with check (true);

alter table public.seller_applications enable row level security;
revoke all on table public.seller_applications from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.seller_applications to pandastore_backend;
create policy pandastore_backend_access on public.seller_applications
    for all to pandastore_backend using (true) with check (true);

alter table public.seller_bank_accounts enable row level security;
revoke all on table public.seller_bank_accounts from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.seller_bank_accounts to pandastore_backend;
create policy pandastore_backend_access on public.seller_bank_accounts
    for all to pandastore_backend using (true) with check (true);

alter table public.sellers enable row level security;
revoke all on table public.sellers from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.sellers to pandastore_backend;
create policy pandastore_backend_access on public.sellers
    for all to pandastore_backend using (true) with check (true);

alter table public.shipments enable row level security;
revoke all on table public.shipments from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.shipments to pandastore_backend;
create policy pandastore_backend_access on public.shipments
    for all to pandastore_backend using (true) with check (true);

alter table public.users enable row level security;
revoke all on table public.users from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.users to pandastore_backend;
create policy pandastore_backend_access on public.users
    for all to pandastore_backend using (true) with check (true);

-- Identity sequences: allow nextval/currval, not setval.
revoke all on sequence public.addresses_address_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.addresses_address_id_seq to pandastore_backend;
revoke all on sequence public.cart_items_cart_item_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.cart_items_cart_item_id_seq to pandastore_backend;
revoke all on sequence public.carts_cart_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.carts_cart_id_seq to pandastore_backend;
revoke all on sequence public.categories_category_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.categories_category_id_seq to pandastore_backend;
revoke all on sequence public.customers_customer_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.customers_customer_id_seq to pandastore_backend;
revoke all on sequence public.notifications_notification_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.notifications_notification_id_seq to pandastore_backend;
revoke all on sequence public.order_groups_order_group_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.order_groups_order_group_id_seq to pandastore_backend;
revoke all on sequence public.order_items_order_item_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.order_items_order_item_id_seq to pandastore_backend;
revoke all on sequence public.orders_order_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.orders_order_id_seq to pandastore_backend;
revoke all on sequence public.payments_payment_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.payments_payment_id_seq to pandastore_backend;
revoke all on sequence public.product_images_image_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.product_images_image_id_seq to pandastore_backend;
revoke all on sequence public.products_product_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.products_product_id_seq to pandastore_backend;
revoke all on sequence public.review_replies_reply_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.review_replies_reply_id_seq to pandastore_backend;
revoke all on sequence public.reviews_review_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.reviews_review_id_seq to pandastore_backend;
revoke all on sequence public.seller_applications_application_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.seller_applications_application_id_seq to pandastore_backend;
revoke all on sequence public.seller_bank_accounts_bank_account_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.seller_bank_accounts_bank_account_id_seq to pandastore_backend;
revoke all on sequence public.sellers_seller_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.sellers_seller_id_seq to pandastore_backend;
revoke all on sequence public.shipments_shipment_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.shipments_shipment_id_seq to pandastore_backend;
revoke all on sequence public.users_user_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.users_user_id_seq to pandastore_backend;

commit;
