application.name=project

datasource.url=${DB_URL}
datasource.username=${DB_USERNAME}
datasource.password=${DB_PASSWORD}

jpa.show-sql=true
jpa.hibernate.ddl-auto=update
jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect