spring.application.name=PandaStore

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.config.import=optional:file:./.env[.properties],optional:file:./backend/.env[.properties]

shipping.fees.default.flash=40.00
shipping.fees.default.kerry=50.00
shipping.fees.default.standard=35.00
shipping.fees.1.flash=40.00
shipping.fees.1.kerry=50.00
shipping.fees.1.standard=35.00
shipping.fees.2.flash=40.00
shipping.fees.2.kerry=50.00
shipping.fees.2.standard=35.00